### PR TITLE
BP-2694 Fix Serialized config issue

### PR DESCRIPTION
**Pull request by gustavorof**

### CODE REVIEW

**Review by LucianTuriacArnia — APPROVED** [review]

**Comment by LucianTuriacArnia** [comment]
Thank you @gustavorof for discovering and addressing this issue in the Buckaroo_Magento2Analytics module for Magento 2.4.5-p3. Please let us know if you're still able to reproduce this bug after the merge.

**Comment by Buckaroo-Rens** [comment]
@gustavorof Can you provide us with a update from your side?

**Comment by gustavorof** [comment]
Hello @Buckaroo-Rens, I'm sorry the late response. Indeed it's working fine now

**Comment by Buckaroo-Rens** [comment]
Thanks for your confirmation @gustavorof!

**Pull request merged**
